## import libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load dataset

In [2]:
df = pd.read_csv("../Dataset/Unclean_Retail_Sales_Dataset.csv")
df

,Transaction_ID,Customer_ID,Product_Category,Product_Name,Quantity,Unit_Price,Total_Amount,Purchase_Date,Customer_City,Payment_Method,Customer_Age,Customer_Gender
0,T0001,C0126,Sports,Football,1,25000,25000,2025-05-21,karachi,Credit Card,65.0,Male
1,T0002,C0048,Sports,Football,7,500,3500,2025-01-16,KARACHI,Credit Card,50.0,Male
2,T0003,C0302,Beauty,Skin Care,7,1000,7000,2025-08-18,lahore,Cash,28.0,Female
3,T0004,C0053,Grocery,Snacks,3,1000,3000,2025-06-22,Lahore,Online Payment,24.0,Female
4,T0005,C0275,Grocery,Snacks,1,25000,25000,2025-08-24,ISLAMABAD,Online Payment,23.0,Female
...,...,...,...,...,...,...,...,...,...,...,...,...
1220,T0381,C0063,Electronics,Smart Watch,2,50000,100000,2025-03-13,Karachi,Cash,32.0,Male
1221,T0610,C0376,Grocery,Rice,5,10000,50000,2025-01-21,Karachi,Debit Card,22.0,Male
1222,T0677,C0459,Furniture,Table,8,50000,400000,2025-10-02,Islamabad,Online Payment,44.0,Male
1223,T0345,C0191,Grocery,Rice,6,2500,15000,2025-02-12,Faisalabad,EasyPaisa,28.0,Male
1224,T0110,C0391,Beauty,Shampoo,6,2500,15000,2025-10-10,Peshawar,Online Payment,47.0,Female

### check 1st 5 rows

In [3]:
df.head()

,Transaction_ID,Customer_ID,Product_Category,Product_Name,Quantity,Unit_Price,Total_Amount,Purchase_Date,Customer_City,Payment_Method,Customer_Age,Customer_Gender
0,T0001,C0126,Sports,Football,1,25000,25000,2025-05-21,karachi,Credit Card,65.0,Male
1,T0002,C0048,Sports,Football,7,500,3500,2025-01-16,KARACHI,Credit Card,50.0,Male
2,T0003,C0302,Beauty,Skin Care,7,1000,7000,2025-08-18,lahore,Cash,28.0,Female
3,T0004,C0053,Grocery,Snacks,3,1000,3000,2025-06-22,Lahore,Online Payment,24.0,Female
4,T0005,C0275,Grocery,Snacks,1,25000,25000,2025-08-24,ISLAMABAD,Online Payment,23.0,Female

### check rows and columns

In [4]:
df.shape

(1225, 12)

### check datatypes and missing values

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225 entries, 0 to 1224
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1225 non-null   object
 1   Customer_ID       1225 non-null   object
 2   Product_Category  1225 non-null   object
 3   Product_Name      1225 non-null   object
 4   Quantity          1225 non-null   int64
 5   Unit_Price        1225 non-null   int64
 6   Total_Amount      1225 non-null   int64
 7   Purchase_Date     1225 non-null   object
 8   Customer_City     1185 non-null   object
 9   Payment_Method    1205 non-null   object
 10  Customer_Age      1205 non-null   float64
 11  Customer_Gender   1225 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 115.0+ KB

### check statistical summary

In [6]:
df.describe()

          Quantity    Unit_Price   Total_Amount  Customer_Age
count  1225.000000   1225.000000    1225.000000   1205.000000
mean      4.530612  13340.408163   62013.061224     41.582573
std       2.327567  16713.868204   93831.432133     14.339182
min      -2.000000   -500.000000     500.000000     18.000000
25%       2.000000   1000.000000    5000.000000     29.000000
50%       5.000000   5000.000000   20000.000000     41.000000
75%       7.000000  25000.000000   70000.000000     54.000000
max       8.000000  50000.000000  400000.000000    150.000000

### check missing values

In [7]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Product_Category     0
Product_Name         0
Quantity             0
Unit_Price           0
Total_Amount         0
Purchase_Date        0
Customer_City       40
Payment_Method      20
Customer_Age        20
Customer_Gender      0
dtype: int64

## Handle Missing Values

In [ ]:
# Handle missing values in customer city  by replacing with 'Unknown'
df["Customer_City"] = df["Customer_City"].fillna("Unknown")

In [ ]:
# Handle missing values in payment method by replacing with 'Unknown'
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

In [10]:
# Handle missing values in numerical column (customer age) by replacing with the median age
df["Customer_Age"] = df["Customer_Age"].fillna(df["Customer_Age"].median())

In [11]:
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Total_Amount        0
Purchase_Date       0
Customer_City       0
Payment_Method      0
Customer_Age        0
Customer_Gender     0
dtype: int64

### check duplicates

In [12]:
df.duplicated().sum()

np.int64(24)

### drop duplicates

In [13]:
df.drop_duplicates(
    inplace=True
)

In [14]:
df.duplicated().sum()

np.int64(0)

## Standarized text columns

In [15]:
# Standardize city names by converting to title case
df["Customer_City"] = df["Customer_City"].str.title()

In [16]:
# Remove leading/trailing whitespaces and convert product categories to title case
df["Product_Category"] = df["Product_Category"].str.strip().str.title()

In [17]:
# Remove leading/trailing whitespaces and convert payment methods to title case
df["Payment_Method"] = df["Payment_Method"].str.strip().str.title()

In [18]:
# Verify the unique values in the Customer_City column
df["Customer_City"].unique()

array(['Karachi', 'Lahore', 'Islamabad', 'Multan', 'Peshawar',
       'Faisalabad', 'Unknown'], dtype=object)

### convert purchase dates into consistent datetime format

In [19]:
df["Purchase_Date"] = pd.to_datetime(
    df["Purchase_Date"],
    errors="coerce"
)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1202
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1201 non-null   object
 1   Customer_ID       1201 non-null   object
 2   Product_Category  1201 non-null   object
 3   Product_Name      1201 non-null   object
 4   Quantity          1201 non-null   int64
 5   Unit_Price        1201 non-null   int64
 6   Total_Amount      1201 non-null   int64
 7   Purchase_Date     1191 non-null   datetime64[ns]
 8   Customer_City     1201 non-null   object
 9   Payment_Method    1201 non-null   object
 10  Customer_Age      1201 non-null   float64
 11  Customer_Gender   1201 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 122.0+ KB

In [21]:
# Drop rows where Purchase_Date is missing (NaT)
df = df.dropna(subset=["Purchase_Date"])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1191 entries, 0 to 1202
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1191 non-null   object
 1   Customer_ID       1191 non-null   object
 2   Product_Category  1191 non-null   object
 3   Product_Name      1191 non-null   object
 4   Quantity          1191 non-null   int64
 5   Unit_Price        1191 non-null   int64
 6   Total_Amount      1191 non-null   int64
 7   Purchase_Date     1191 non-null   datetime64[ns]
 8   Customer_City     1191 non-null   object
 9   Payment_Method    1191 non-null   object
 10  Customer_Age      1191 non-null   float64
 11  Customer_Gender   1191 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 121.0+ KB

## Handle Invalid Values

In [23]:
# Check quantity column
df[df["Quantity"]<=0]

,Transaction_ID,Customer_ID,Product_Category,Product_Name,Quantity,Unit_Price,Total_Amount,Purchase_Date,Customer_City,Payment_Method,Customer_Age,Customer_Gender
100,T0101,C0169,Grocery,Snacks,-2,50000,100000,2025-03-24,Multan,Easypaisa,49.0,Female

In [ ]:
# Remove 0 and negative values keep only possitive quantities
df=df[
    df["Quantity"]>0
]

In [25]:
# check unit price column
df[df["Unit_Price"]<=0]

,Transaction_ID,Customer_ID,Product_Category,Product_Name,Quantity,Unit_Price,Total_Amount,Purchase_Date,Customer_City,Payment_Method,Customer_Age,Customer_Gender
101,T0102,C0162,Sports,Dumbbell,1,-500,5000,2025-02-15,Unknown,Debit Card,25.0,Female

In [26]:
#Remove 0 and negative values keep only possitive Unit prices
df=df[
    df["Unit_Price"]>0
]

In [27]:
# check customer age column
df[df["Customer_Age"]<=0]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Product_Category, Product_Name, Quantity, Unit_Price, Total_Amount, Purchase_Date, Customer_City, Payment_Method, Customer_Age, Customer_Gender]
Index: []

In [28]:
# Remove unrelastic ages , keep only reliastic age betwee 10 and 100
df=df[
    (df["Customer_Age"]>=10)
    &
    (df["Customer_Age"]<=100)
]

### verify clean dataset

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1188 entries, 0 to 1202
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1188 non-null   object
 1   Customer_ID       1188 non-null   object
 2   Product_Category  1188 non-null   object
 3   Product_Name      1188 non-null   object
 4   Quantity          1188 non-null   int64
 5   Unit_Price        1188 non-null   int64
 6   Total_Amount      1188 non-null   int64
 7   Purchase_Date     1188 non-null   datetime64[ns]
 8   Customer_City     1188 non-null   object
 9   Payment_Method    1188 non-null   object
 10  Customer_Age      1188 non-null   float64
 11  Customer_Gender   1188 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 120.7+ KB

In [30]:
# check duplicates 
print("Remaining Duplicates:", df.duplicated().sum())

Remaining Duplicates: 0

In [31]:
df.describe()

,Quantity,Unit_Price,Total_Amount,Purchase_Date,Customer_Age
count,1188.000000,1188.000000,1188.000000,1188,1188.000000
mean,4.513468,13276.094276,61519.360269,2025-06-27 14:49:41.818181632,41.483165
min,1.000000,500.000000,500.000000,2025-01-01 00:00:00,18.000000
25%,2.000000,1000.000000,5000.000000,2025-03-23 00:00:00,29.000000
50%,5.000000,5000.000000,20000.000000,2025-06-26 00:00:00,41.000000
75%,7.000000,25000.000000,70000.000000,2025-09-30 00:00:00,53.000000
max,8.000000,50000.000000,400000.000000,2025-12-31 00:00:00,65.000000
std,2.314524,16634.581500,93116.234647,NaN,13.869006

### Now save cleaned Dataset

In [32]:
df.to_csv(
    "../Dataset/Cleaned_Retail_Sales_Dataset.csv",
    index=False
)

## OBSERVATIONS:  
- Missing values were identified and handled.
- Duplicate transactions were removed.
- Text fields were standardized.
- Date formats were converted into datetime format.
- Invalid numerical values were removed.
- Clean dataset was exported for further analysis.
The cleaned dataset is now ready for Exploratory Data Analysis and Dashboard development.